

```{r}
#number of clusters in the population, N=100
N = 100

#number of elements in each cluster, M_i, given in problem statement as
#M_i = 100 for first 40 clusters; M_i = 300 for next 40 clusters; M_i = 500 for last 20 clusters
Mis = c(rep(100, 40), rep(300, 40), rep(500, 20))

#number of elements in the population
M0 = sum(Mis)

#now generate the data according to problem statement

#this will be the population data values
y = c()

#this will be an index for the cluster
clusterindex = c()

#this will include the Mis for each ssu
clusterMis = c()

#this will be the mean and sd of each cluster
clustermean = c(rep(40, 40), rep(10, 40), rep(100, 20))
clustersd = c(rep(5, 40), rep(2, 40), rep(20,20))
```


now we make the data by looping through the clusters
if you need to run this loop again, re-set y, clusterindex, and clusterMis to be empty..

```{r}

#now we make the data by looping through the clusters
#if you need to run this loop again, re-set y, clusterindex, and clusterMis to be empty..

for(i in 1:N) {
  temp = rep(i, Mis[i])
  clusterindex = c(clusterindex, temp)
  
  temp = rep(Mis[i], Mis[i])
  clusterMis = c(clusterMis, temp)
  
  temp = rnorm(Mis[i], clustermean[i], clustersd[i])
  y = c(y, temp)
}
```



```{r}

#put the cluster index and data values together in the population universe U

U = cbind(cluster = clusterindex, Mis = clusterMis, y = y)

#you can use the U that you generated for the simulation.

##here are some commands for taking a one stage cluster sample from U

nclus = 10
clussampind = sample(1:N, nclus, replace = F)

#now collect the data for all sampled clusters
#first column has the cluster labels
clussamp = U[U[,1] %in% clussampind,]

clussamp
```

